### ISSUE TITLE
Support HTTP authentication to API server

### ISSUE THREAD

**Issue by jelco** [tcplugins/tcWebHooks#19] opened 2015-12-07 01:21 UTC
Currently there is no way to use HTTP Basic Auth on the API server (that I can see) - the only form of authorization is the proxy authentication, which isn't sufficient. In the most basic form just allowing username and password parameters that are put into a HTTP Authorization header would probably be alright. If you want to make it really clever, you could also include the option of using bearer token authentication (for OAuth support), although for me personally that's currently not required.

My use case is integration with the Bitbucket Cloud REST API, which uses HTTP authentication instead of putting tokens in URLs like HipChat and Slack.

**Comment by netwolfuk** [comment] 2015-12-07 21:38
It would makes sense to provide an authentication interface to the webhook, and implement Basic Auth as a first cut. I'll have a think about it. Thanks for the suggestion.

**Comment by jelco** [comment] 2016-02-15 07:49
Any update on when you'll have some time to look into this? This is genuinely the only thing that is keeping me from using this - otherwise it's the best fit out there. :)

**Comment by netwolfuk** [comment] 2016-02-15 09:20
I'm so sorry. Your request came in just as I was travelling abroad for work, and it's been pretty crazy at our house since Christmas.
Would you want per webhook credentials? I can't imagine a single user/pass across the TeamCity instance would be much use.

**Comment by jelco** [comment] 2016-02-15 12:37
No worries, I can relate. :) For me a per-project set of credentials would also be fine, but per-webhook is also fine and definitely more flexible. Whichever is easiest for you, I guess.

**Comment by netwolfuk** [comment] 2016-02-19 08:24
Hi @jelco 

I've implemented this in a way that should allow for some flexibility in the future.
I've written an implementation which supports User/Pass authentication. It should work with Basic Auth, Digest and NTLM, although I've only tested Basic.

You need to add a section like this to the webhook config (by manually editing a webhook's XML config)...

`       <auth type="userpass" enabled="true">
       	  <auth-parameters>
		    <param name="username" value="user1" />
		    <param name="password" value="user1pass" />
		    <param name="realm" value="TestRealm" />
	      </auth-parameters>
      </auth>`

You can download a build from the link below. Just login as guest if prompted.
https://teamcity.jetbrains.com/repository/download/WebHooksAndOtherPlugins_TcWebHooksBranch09xX/705176:id/tcWebHooksPlugin-0.9.59.78.zip

If you could test that I would appreciate it.
Next is to write up the docs and then to merge these changes into the custom-templates branch.

**Comment by netwolfuk** [comment] 2016-02-22 12:37
The custom-templates branch now has this change merged too. Feel free to try this:
https://teamcity.jetbrains.com/repository/download/WebHooksAndOtherPlugins_TcWebHooksBranch09xX/707558:id/tcWebHooksPlugin-1.1.63.115.zip

**Comment by jelco** [comment] 2016-02-23 09:52
Now it's my turn to apologize for the delay - I've been down with the flu over the last few days so unfortunately I didn't have a chance to try this. I'll have a go at it later this week and get back to you with the results.

Thanks!

**Comment by jelco** [comment] 2016-03-10 00:32
Well, it took me a while to find the time, but I finally got around to it! The bottom line is that I got it to work, although unfortunately it wasn't exactly plug-and-play.

I found that the Bitbucket API doesn't return a 401 if it's accessed without Authorization headers, but instead returns a 403 rightaway. The HTTP client library you're using by default will only submit the Authorization headers after it receives a 401 response, and basically seems to consider a 403 as too big an error to still attempt authorization. (I'm not sure if Bitbucket are sticking to the applicable RFCs here, but in any case it's just something we have to deal with.) The fix is enabling pre-emptive authorization, which I managed to do by adding this line to tcwebhooks-core/src/main/java/webhook/teamcity/auth/UsernamePasswordAuthenticator.java:

`client.getParams().setAuthenticationPreemptive(true);`

You might want to make this a configurable option, perhaps something like `<auth type="userpass" enabled="true" preemptive="true">`. It probably won't do any harm in most situations to have it on by default, considering it'll only be authenticating if you provide credentials anyway, but it does notably break one test in its current form. So yeah, it's up to you really - I can live with it either way.

In any case, with the above change I'm able to integrate fully with the Bitbucket API for our purposes, so you've made my life a lot easier this way. Thank you very much for the good work! If you need me to test another version, just let me know.

**Comment by netwolfuk** [comment] 2016-03-10 04:23
Thanks for all your work on testing this. Sorry it wasn't so straight forward. 
If you think preemptive applies to all auth types I can add it there as you suggested. If it just applies to basic auth then it should be added as an auth param. Thoughts? I'm happy to put it into the most appropriate place.

**Comment by jelco** [comment] 2016-03-10 08:22
I think in all authentication situations you want to send the Authorization header rightaway - waiting for a 401 response basically means it takes roughly twice as long because you always require 2 requests (a non-Auth request with a 401 response, then an Auth request with a 2xx response). 

However, I've seen a lot of weird APIs over the years, including some that break if you send Auth headers on a public page. I think for those APIs you want to leave the option open to stick to waiting for a 401 before sending the headers.

My suggestion would be to have it as an option that defaults to true. It keeps the flexibility but ensures that in most situations the minimal configuration is the right one.

**Comment by netwolfuk** [comment] 2016-03-10 09:30
Ok. Sounds good. I'll enable it by default at the auth level. I'll update this ticket when done.

**Comment by netwolfuk** [comment] 2016-03-10 11:02
A new build of 0.9 is available here: https://teamcity.jetbrains.com/repository/download/WebHooksAndOtherPlugins_TcWebHooksBranch09xX/719445:id/tcWebHooksPlugin-0.9.65.79.zip

**Comment by jelco** [comment] 2016-03-11 11:46
I think my configuration doesn't work without the custom-templates because there are some variable substitutions in the URL (Bitbucket places the commit ID in the URL instead of the request body) which don't work with your provided zip. I tried to use the zip artefact from the latest custom-templates build after the last merge, but that one breaks:

`WARN - ildServer.util.EventDispatcher - Error in event handler: java.lang.IllegalStateException: Unable to create settings for webhooks; corresponding factory was not registered (e
nable debug to see stacktrace)`

**Comment by netwolfuk** [comment] 2016-03-11 19:19
Sorry. I'm not sure why I thought you were using 0.9, I'll dig into the issues with 1.1. I have not actually tested 1.1 since the merge.

**Comment by netwolfuk** [comment] 2016-03-12 01:00
Yeah, so that was a silly mistake completely unrelated to the auth stuff. A new 1.1 build is available at https://teamcity.jetbrains.com/repository/download/WebHooksAndOtherPlugins_TcWebHooksBranch09xX/721553:id/tcWebHooksPlugin-1.1.68.119.zip

**Comment by netwolfuk** [comment] 2016-03-17 05:35
Hi @jelco. Is this working for you? I'd like to do the merge on master and release a new 0.9 and 1.1 versions.

**Comment by jelco** [comment] 2016-03-17 07:50
I'm at a conference right now so unfortunately I don't have the time to check it, but I'll try it and get back to you first thing next week!

**Comment by netwolfuk** [comment] 2016-03-17 08:00
That's cool. Thanks.

**Comment by jelco** [comment] 2016-03-21 15:45
The pre-emptive setting does work, although it doesn't appear to be set to true by default. I'm guessing [this line](https://github.com/tcplugins/tcWebHooks/blob/custom-templates/tcwebhooks-core/src/main/java/webhook/teamcity/settings/WebHookConfig.java#L48) is to blame for that.

Save that tidbit I think it's done!

**Comment by netwolfuk** [comment] 2016-03-21 18:31
Ah. I see that is fixed on the branch. I must not have merged it in to the 1.1 branch (custom-templates)

**Comment by alexvaccaro** [comment] 2016-05-16 15:09
Hi @netwolfuk, I was also looking at authenticating the webhook request and I can confirm basic authentication works :+1: 
.
I also tried to get it working with NTLM but to no avail, You stated that this should work with NTLM so I wonder if I am doing anything wrong, am I right to assume that for ntlm the authentication configuration should look something like this?

```
      <auth enabled="true" type="ntlm" preemptive="true">
        <auth-parameters>
          <param name="password" value="password" />
          <param name="username" value="name" />
          <param name="realm" value="domain" />
        </auth-parameters>
      </auth>

**Comment by netwolfuk** [comment] 2016-05-16 22:53
I don't really have a way to test NTLM auth, but it's handled by the Apache HTTP client, not by my code.
Technically, it's still just userpass, so try this...
```
      <auth enabled="true" type="userpass" preemptive="true">
        <auth-parameters>
          <param name="password" value="password" />
          <param name="username" value="name" />
          <param name="realm" value="domain" />
        </auth-parameters>
      </auth>
```
Also, I'm not sure if the realm is required. I don't know enough about NTLM to determine that.

**Comment by alexvaccaro** [comment] 2016-05-17 15:36
OK, thanks. I have tried with and without realm, but I cannot get it to work.

I am no Java developer so I am no expert on how Apache HTTP client handles this, but I see from the online documentation that NTCredentials rather than UsernamePasswordCredentials should be used when establishing an NTLM connection, see https://hc.apache.org/httpcomponents-client-ga/tutorial/html/authentication.html and http://hc.apache.org/httpclient-3.x/authentication.html, is the code handling this scenario? If not I will be using basic authentication for now and perhaps one day get one of my Java developer friends to help me out implementing this :)

**Comment by netwolfuk** [comment] 2016-05-17 22:17
Thanks for doing that investigation. That shouldn't be too difficult to implement. Although I do think the version of http client in using is rather old so that will need to be updated.

**Comment by netwolfuk** [comment] 2016-05-18 12:52
@alexvaccaro Please take a look at #33

**Comment by netwolfuk** [comment] 2016-07-18 12:02
I'll close this. HTTP is supported. It's just NTLM that not working, and that has its own ticket #33

**Closed by netwolfuk** 2016-07-18 12:02 UTC
Labels: enhancement
