### ISSUE TITLE
No Documentation on Encoding Newlines into Webhook with webhook.body

### ISSUE THREAD

**Issue by btzrl6** [tcplugins/tcWebHooks#75] opened 2017-11-03 21:02 UTC
Is there a way to do this that I am missing?  I am using a TeamCity environment variable to use a webhook into a Office365/Teams API endpoint.

```
$TeamsNotificationTemplate = {
@"
Report: $ReportURL
$($Thing0.Count) new and $($Thing1.Count) recurring
Thing2: $($Thing2.Count)
Thing3: $($Thing3.Count)
Thing4: $($Thing4.Count)
"@  }

$TeamsNotificationMessage = &$TeamsNotificationTemplate
Write-Host ("##teamcity[setParameter name='env.TeamsNotificationMessage' value='$TeamsNotificationMessage']")
```

I have the following webhook template configured for this series of jobs:

```
{"title":"Report", "text":"${buildStateDescription}: ${ProjectPath} ${env.TeamsNotificationMessage}"}
```

This is what is in the build log for the job, and Teams notification is completely blank where that data should be, even if it shows up in the logs.  Loading normal text, obviously without newlines, works, so I assume I did it wrong.  The space after `value='` is a newline from the Powershell heredoc string as well I think.   I double checked the deployed script and marked up whitespace.  There is now space after the first `@"`.

```
 ##teamcity[setParameter name='env.TeamsNotificationMessage' value=' Report: https://www.reporturl.tld/subdir/file.php?rid=1111111&projectid=1
 167 new and 83 recurring:
 
 Thing2: 32
 Thing3: 64
 Thing4: 238']
```

**Comment by netwolfuk** [comment] 2017-11-03 21:43
I'm not in front of a computer at the moment, so can't check this, but you could try `\n` or `\r\n` (since it's Windows).

Also, I'm assuming this is a JSON string, so there might be a way we are supposed to encode `\n` in JSON.

**Comment by btzrl6** [comment] 2017-11-06 02:51
Ok, I will look into those and report back.

**Comment by netwolfuk** [comment] 2017-11-06 03:55
With regards to encoding `\n` in JSON, it looks like it's `\\n` in most languages. Eg, escape the `\` with another `\` so that is it still `\n` when it arrives at the destination (teams in this instance).

**Comment by btzrl6** [comment] 2017-11-06 14:55
Yes, it appears so.  I am still experimenting with this on personal builds.  Thanks for the pointers.

**Comment by btzrl6** [comment] 2017-11-08 04:47
So far I have tried `\n` and `\\n` assuming the former might still be escaped, as bizarrely in both cases I still see the build log with new lines, not encoding them.  I am trying some other stuff and will follow up if I am still unsuccessful.

**Comment by netwolfuk** [comment] 2017-11-08 05:23
I'm so sorry. I meant to look at this last night, but was distracted by coding. I'll try tonight to reproduce what you're seeing.

**Comment by netwolfuk** [comment] 2017-11-08 05:25
You could also try `\\\n`. So that the `\` is escaped as well as the `\n`.

**Comment by netwolfuk** [comment] 2017-11-08 11:13
I don't have a windows machine, and I don't have access to teams, so can't do much testing. However I have done the following:

Created a webhook.body the similar to yours:
```
{"title":"Report", "text":"${buildStateDescription}: ${ProjectPath} \n ${env.TeamsNotificationMessage}"}
```

Created a build script in ANT which outputs both newlines and line with `\n` within them.

    <project>
    <echo message="##teamcity[setParameter name='ProjectPath' value='Line1
    Line2
    Line3']"/>
    <echo message="##teamcity[setParameter name='env.TeamsNotificationMessage' value='Line4 \n Line5 \n Line6']"/>
</project>

Configured a webhook to point to the test endpoint (http://localhost:8111/webhooks/endpoint.html)
I can see the following output at http://localhost:8111/webhooks/endpoint-viewer.html
```
{
  "title": "Report",
  "text": "finished: Line1 Line2 Line3 \n Line4 \n Line5 \n Line6"
}
```

In the logs I am seeing the "ProjectPath line all squashed back into one line.
```
[23:45:25][Step 1/1] echo
[23:45:25][echo] ##teamcity[setParameter name='ProjectPath' value='Line1 Line2 Line3']
[23:45:25][Step 1/1] echo
[23:45:25][echo] ##teamcity[setParameter name='env.TeamsNotificationMessage' value='Line4 \n Line5 \n Line6']
```

So it appears I'm not having any more luck than you. In fact, TeamCity (or ANT) is not letting the newlines work at all. 
Next I'll try with a bash script.

**Comment by netwolfuk** [comment] 2017-11-08 11:52
I have successfully created a multiline output using printf in bash. 
```
#!/bin/bash
printf "##teamcity[setParameter name='env.TeamsNotificationMessage' value='test1\ntest2\ntest3\n\n']"
```

And I can see it output in the log.
```
[00:27:19][Step 2/2] ##teamcity[setParameter name='env.TeamsNotificationMessage' value='test1
[00:27:19][Step 2/2] test2
[00:27:19][Step 2/2] test3
[00:27:19][Step 2/2] 
[00:27:19][Step 2/2] ']
```

However. If I look in the Parameters of the build after it has run, it is not defining the parameter "env.TeamsNotificationMessage". It simply never gets defined if it goes over multiple lines.
Does the multi-line setParameter  command work for you? 

So, the only way I can see is to use `\n` as part of the message, and hope that Teams does the correct thing when it reads it.

To get around any escaping issues between the build log and the webhook, you could try something like...
```
{"title":"Report", "text":"${buildStateDescription}: ${ProjectPath} Report: ${ReportURL}\n${Thing0.Count} new and ${Thing1.Count} recurring\nThing2: ${Thing2.Count}\nThing3: ${Thing3.Count}\nThing4: ${Thing4.Count}" }
```
and then 
```
##teamcity[setParameter name='Thing0.Count' value='167']
```
to define each param for the template.

I'm not sure if it will help if Teams is ignoring the `\n` though.

**Comment by netwolfuk** [comment] 2017-11-08 12:24
I don't know if you have permission to install the latest plugin on your TC server, but if you want to try the very [latest build of tcwebhooks](https://teamcity.jetbrains.com/viewLog.html?buildId=1221240&buildTypeId=WebHooksAndOtherPlugins_TcWebHooksBranch09xX&tab=artifacts), you could also create a template and use that with your webhook.

Download and install the plugin.zip files, copy and paste the following into `BuildServer/config/webhook-templates.xml`  and then restart teamcity.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<webhook-templates>
    <webhook-template id="issue_75_test" enabled="true" rank="1" format="jsonTemplate">
        <default-template use-for-branch-template="true">{"title":"Report",
"text":"${buildStateDescription}: ${ProjectPath}
Report: ${ReportURL}
${Thing0.Count} new and ${Thing1.Count} recurring
Thing2: ${Thing2.Count}
Thing3: ${Thing3.Count}
Thing4: ${Thing4.Count}
"} </default-template>
        <default-branch-template></default-branch-template>
        <template-description>Test Template for Issue 75</template-description>
        <template-tool-tip></template-tool-tip>
        <preferred-date-format></preferred-date-format>
        <templates max-id="0"/>
    </webhook-template>
</webhook-templates>
```

You can then create a new webhook and choose the new template called "Test Template for Issue 75".
Of course, you'd need to define parameters for ReportURL and the Thing counts.  eg:
`##teamcity[setParameter name='Thing0.Count' value='167']`

**Comment by btzrl6** [comment] 2017-11-08 13:01
So am I understanding my only option is the template or manually setting up each variable in the template or specific version of the build?  I suspected the latter from the onset, but was trying to test this for myself anyway.

I do not have permissions for installing the updated plugin, but my developer teams will be interested nonetheless.  I will determine the best way for our environment.  Thanks for your help.

**Comment by netwolfuk** [comment] 2017-11-08 16:18
My concern is that we might do all this and it still not actually work.

Have you managed to get the new lines working by manually POSTing the data straight to teams? 

That would prove whether what you are trying to do is even possible.

**Comment by btzrl6** [comment] 2017-11-09 14:27
You make a good point.  Let me try with curl/CLI tools and get back to you.  Yesterday got away from me.

**Comment by btzrl6** [comment] 2017-11-22 21:43
Sorry for the delay as I dropped the ball. I will look at this in a little bit and get back to you.

**Comment by btzrl6** [comment] 2017-11-30 14:21
Yep, I never got around to this as agreed.  I will be testing this more thoroughly now that I have some time to do so.

**Comment by netwolfuk** [comment] 2018-01-25 21:01
Hi @btzrl6 

I will close this out, as it feels like it's out of scope for tcWebHooks until we can prove that teams supports the format you want.
 I'll let you do more testing, and you can raise a new ticket if you would like more assistance from me.

**Closed by netwolfuk** 2018-01-25 21:01 UTC
Labels: awaiting feedback
