### ISSUE TITLE
Webhook for Discord with Slack JSON not working

### ISSUE THREAD

**Issue by padawahn** [tcplugins/tcWebHooks#86] opened 2017-12-31 01:39 UTC
## Expected Behavior

Posting to discord webhook link with slack payload is supposed to work.
I tested this by manually posting the payload that is sent from the plugin through a third party website.
[https://discordapp.com/developers/docs/resources/webhook#execute-slackcompatible-webhook](https://discordapp.com/developers/docs/resources/webhook#execute-slackcompatible-webhook)

## Current Behavior

There is an error when the post of the webhook happens.

`INFO -   jetbrains.buildServer.SERVER - WebHookListener :: WebHook triggered : <WEBHOOKURL> using format jsontemplate returned 403 null 
[2017-12-30 19:15:04,297]   WARN -   jetbrains.buildServer.SERVER - WebHookListener ::  WebHook (url: <WEBHOOKURL> proxy: null:0) returned HTTP status 403 
[2017-12-30 19:15:04,297]  ERROR -   jetbrains.buildServer.SERVER - WebHookListener :: 7d0f32dc-24e0-43bb-82c3-8f6f56086929 :: WebHook endpoint returned non-2xx response (Forbidden) `

## Steps to Reproduce (for bugs)

1. Install Webhooks
2. Add Webhook to Build
3. Select payload to be "Slack.com Compact Notification (JSON)" and add a discord URL with /slack at the end
4. Run Build
5. Notice in Administration/Webhooks that there is errors

## Your Environment

* tcWebHooks Version: 1.1-alpha14.206.282
* TeamCity Version: 2017.2.1 (build 50732)
* TeamCity server Operating System: Windows 10
* Are you using a WebHook Template?: Slack.com Compact Notification (JSON)

**Comment by netwolfuk** [comment] 2017-12-31 01:54
Without looking into this at all, I'd just say that forbidden is an odd response to return. Do you need to pass in an authentication token in the URL?

**Comment by padawahn** [comment] 2017-12-31 02:12
no authentication.
I tested this on the website hurl.it and was able to make it work there by just putting the discord URL in the post line and your template from the json compact notification into the body.
didn't change anything on the header and no authentication required.

**Comment by netwolfuk** [comment] 2017-12-31 02:43
Yeah, sorry. I read the discord docs. The authentication is based on the hook id (which is part of the URL).

I signed up to discord and I can reproduce this error (403) forbidden message.

**Comment by padawahn** [comment] 2017-12-31 02:43
I wonder if it has to do with the Http Client Version you are sending as?

[https://stackoverflow.com/questions/12059278/how-to-post-json-request-using-apache-httpclient](https://stackoverflow.com/questions/12059278/how-to-post-json-request-using-apache-httpclient)

````
StringEntity requestEntity = new StringEntity(
    JSON_STRING,
    ContentType.APPLICATION_JSON);

HttpPost postMethod = new HttpPost("http://example.com/action");
postMethod.setEntity(requestEntity);

HttpResponse rawResponse = httpclient.execute(postMethod);
````

seems to be the latest way to do things instead of 

`postMethod.setRequestEntity(requestEntity);`

**Comment by netwolfuk** [comment] 2017-12-31 02:49
But executing from curl works perfectly.

**Comment by netwolfuk** [comment] 2017-12-31 03:00
You could be onto something there, although I'd say it's more likely because it's the really old client. There is httpclient and httpcomponents. I am using the older one, and really should upgrade it.

**Comment by padawahn** [comment] 2017-12-31 14:20
Yes it seems the httpclient has been replaced in the httpcomponents.

> Commons HttpClient 3.x codeline is at the end of life. All users of Commons HttpClient 3.x are strongly encouraged to upgrade to HttpClient 4.1.
[HttpClient 4.5](http://hc.apache.org/httpcomponents-client-4.5.x/examples.html)

**Comment by netwolfuk** [comment] 2018-01-01 09:49
FYI. httpclient 4.5.4 works perfectly with discord (testing with the compact notification).

![image](https://user-images.githubusercontent.com/88687/34466829-e67f1b10-ef45-11e7-8f16-1965bbdf35db.png)

**Comment by padawahn** [comment] 2018-01-01 13:52
Ok I can confirm this seems to work.

**Comment by netwolfuk** [comment] 2018-01-02 07:31
Cool. I'll close this, as the fix will be in the next release.

**Closed by netwolfuk** 2018-01-02 07:31 UTC
Labels: bug

**Comment by netwolfuk** [comment] 2018-01-08 08:48
release released
