### ISSUE TITLE
Project versioned settings log constant comment "no comments"

### ISSUE THREAD

**Issue by ghost** [tcplugins/tcWebHooks#164] opened 2020-09-01 08:55 UTC
## Expected Behavior
Git log of TeamCity project configuration versioned settings has clarifications of what was changed.

## Current Behavior
Any changes of configuration of TeamCity webhooks are logged as "no comments" (compare to messages below on changes of other TeamCity areas):
![Screen Shot 2020-09-01 at 11 45 10](https://user-images.githubusercontent.com/41187778/91828887-6507d000-ec49-11ea-8d3d-bfddc078e17d.png)

## Steps to Reproduce (for bugs)
1. Go to Administration -> Root Project -> Versioned Settings ( http://1.2.3.4:8111/admin/editProject.html?projectId=_Root&tab=versionedSettings )
2. Enable synchronization with remote git repo
![Screen Shot 2020-09-01 at 11 52 44](https://user-images.githubusercontent.com/41187778/91829096-ad26f280-ec49-11ea-983a-3046ee84bd4d.png)
3. make changes in WebHook configuration
4. open git log of the TeamCity changes and compare webhooks-related changes vs other changes

## Your Environment

* tcWebHooks Version: 1.1.362.398
* TeamCity Version: 2020.1.3
* TeamCity server Operating System: ubuntu
* Are you using a WebHook Template?: not applicable

**Comment by netwolfuk** [comment] 2020-09-01 19:52
Hi @schernov-xo. I'll have a look too see if there is a way I can pass a comment when I persist the hook. That code predates any of the settings stuff. I'm using the method of storing settings which is compatible with TC9 and below.

I'll take a later in the week when I'm back from vacation. No internet here and not computer! 😁

**Comment by netwolfuk** [comment] 2020-09-04 19:34
Hi @schernov-xo   I had a look a the code, and I can't see how the comment could be set using the `plugin-settings.xml` storage method. I have asked a question here: https://youtrack.jetbrains.com/issue/TW-67532, however I don't know if it's going to be possible.

**Comment by netwolfuk** [comment] 2020-09-07 19:49
Anton from Jetbrains has replied and shown me how to do this. I'm embarrassed to say I was looking at the wrong code, but he found it. 

I'll refactor that code this week and get it out as part of 1.2.0 alpha7. I see you're using 1.1, so I'll back port it and do a 1.1 release as well. Hopefully this week or over the weekend.

Thanks for raising this issue. I'm happy to make tcWebHooks better!

**Comment by schernov-xo** [comment] 2020-09-08 13:25
Perfect, thanks!

**Comment by netwolfuk** [comment] 2020-09-11 20:53
Hi @schernov-xo 

I have the comments now working. I've not setup a synchronised project yet, but I can see comments appearing in the project audit log. Do you think the comments are right? Should I have more description? 

![image](https://user-images.githubusercontent.com/88687/92971797-39040e80-f4d5-11ea-850f-9034dd43f063.png)

This is on 1.2.0 alpha7 which will be released this weekend. I'll check the code on 1.1.x.x and see how different it is.

**Comment by netwolfuk** [comment] 2020-09-11 21:09
Looking at the 1.1 code, the infrastructure to shift the logic to does not exist. I'll hack it in, considering 1.1 will be old in a few months when 1.2 is finished.

**Comment by schernov-xo** [comment] 2020-09-12 09:42
Thanks. Will check it this weekend

**Comment by schernov-xo** [comment] 2020-09-13 18:53
The issue is still here. I've built the plugin from the latest master (`eb7bafd1`).
![Screen Shot 2020-09-13 at 21 46 38](https://user-images.githubusercontent.com/41187778/93025948-e9bffa00-f60a-11ea-9015-b8643efc1fb4.png)
Setting changed: add trigger event
![Screen Shot 2020-09-13 at 21 50 09](https://user-images.githubusercontent.com/41187778/93025983-30adef80-f60b-11ea-8eb4-f4e18417b616.png)
The commit message is the same
![Screen Shot 2020-09-13 at 21 45 31](https://user-images.githubusercontent.com/41187778/93026011-63f07e80-f60b-11ea-919a-0c96e8de836d.png)

**Comment by netwolfuk** [comment] 2020-09-13 18:56
Eeek. I haven't pushed. Sorry. Had a sick kid all weekend.

**Comment by netwolfuk** [comment] 2020-09-13 19:09
Now pushed to this branch: https://github.com/tcplugins/tcWebHooks/compare/issue_164-add_commit_comment_on_edit

**Comment by netwolfuk** [comment] 2020-09-13 19:12
I have some further tidy up to do in the controller, but this works, and you can test that the messages you get are useful.

Btw. Master is the 1.2.0 branch, so you're now running 1.2.0 alpha 7.

**Comment by schernov-xo** [comment] 2020-09-13 19:28
Now comments are fine. Only one thing - the new version of the plugin does not support legacy configuration format (migration), the webhooks should be recreated:
![Screen Shot 2020-09-13 at 22 16 53](https://user-images.githubusercontent.com/41187778/93026647-48d43d80-f610-11ea-8472-ee0ec93900be.png)
Not a big deal for me, but in some cases it may be a problem.

P.S. thanks!!

**Comment by netwolfuk** [comment] 2020-09-13 19:36
Oh! They definitely should be being migrated. I wonder why that happened. Could you share an old copy of your `plugin-settings.xml` file (with the URL or anything else sensitive removed)?

**Comment by schernov-xo** [comment] 2020-09-13 19:42
Sure. Note: it's not a Root project, it's a project with parent=root
```
<?xml version="1.0" encoding="UTF-8"?>
<settings>
  <webhooks enabled="true">
    <webhook url="https://rest-api-team-XYZ" enabled="true" format="json" template="none">
      <states>
        <state type="buildFixed" enabled="false" />
        <state type="changesLoaded" enabled="false" />
        <state type="responsibilityChanged" enabled="false" />
        <state type="buildFinished" enabled="true" />
        <state type="buildStarted" enabled="true" />
        <state type="buildFailed" enabled="true" />
        <state type="beforeBuildFinish" enabled="false" />
        <state type="buildSuccessful" enabled="true" />
        <state type="buildBroken" enabled="false" />
        <state type="buildInterrupted" enabled="true" />
      </states>
      <build-types enabled-for-all="false" enabled-for-subprojects="false">
        <build-type id="bt23" />
      </build-types>
    </webhook>
  </webhooks>
</settings>
```

**Comment by netwolfuk** [comment] 2020-09-13 19:44
Since you're saving all your changes into git, do you have a version of the plugin settings with the webhooks removed after the upgrade? 

I'm trying to figure out if they were migrated and then removed, or migrated and then disappeared on edit. Or maybe some other event occurred and code did not handle the event correctly. 

You should be able to tell when the file was migrated. It will have added the queue event configuration, and removed the payload format XML attribute.

**Comment by netwolfuk** [comment] 2020-09-13 19:47
Thanks for the XML file. It's a legacy JSON webhook. I'm sure all that code is unit tested. I wonder if it's a combination of the migration and the settings in git. Time for be to setup that git stuff. Sorry about all this.

**Comment by schernov-xo** [comment] 2020-09-13 19:50
Welcome. Glad to help.

**Comment by netwolfuk** [comment] 2020-09-13 21:03
Interesting: Your screenshot of the XML changes show that the webhook was migrated. I can see events for queued, etc.
It looks like you were able edit the webhook then. Was it only after the tcWebhooks version from the issue-164 branch was used that the webhook disappeared?

**Comment by netwolfuk** [comment] 2020-09-13 21:07
Created bug #167

**Comment by schernov-xo** [comment] 2020-09-14 08:23
The problem here to clarify what happened is there was an intermediate version (latest master).
But when latest master was installed, the old hook was on it's place.
Then I installed from the bugfix branch and webhook disappeared.

**Comment by netwolfuk** [comment] 2020-09-14 08:44
Thanks for the clarification. I'm also running the latest branch for this issue, and previously was running a build off the branch that is now master. Except I have been running 1.2 for about 6 months, so it could be an issue with the upgrade.

My hunch is that it's related to the settings in git. I'll need to set that up and test it, but that could be a day or two away.

**Comment by netwolfuk** [comment] 2020-09-18 19:00
Because there is nothing I can do at this time to solve #167, I'll merge this branch in and get alpha 7 released this weekend.

**Closed** 2023-02-02 01:48 UTC
Labels: enhancement, waiting for release, available in alpha or beta release
