### ISSUE TITLE
Java NumberFormatException in TeamCity server log

### ISSUE THREAD

**Issue by westshawn** [tcplugins/tcWebHooks#47] opened 2016-08-30 19:42 UTC
From teamcity-server.log:
`ERROR -   jetbrains.buildServer.SERVER - Error javax.servlet.jsp.JspException: java.lang.NumberFormatException: For input string: "webHookList" while processing request: GET '/webhooks/index.html?buildTypeId=BuildSandbox_TestBuild', from client 10.000.00.00:00000, authenticated as 'aUser' (A User) {id=3}`

The webhooks notification worked as expected.
How serious of an issue is this for the server?

TeamCity 10.0.1 (build 42078)
tcWebHooksPlugin-1.1.109.134

**Comment by netwolfuk** [comment] 2016-08-30 19:48
I've not seen that one before. Could you please post a copy of your plugin-settings.xml? 

I presume the page will have given you an error too, out did this happen when web editing at webhook (which happens via Ajax).

**Comment by netwolfuk** [comment] 2016-08-30 19:50
Also if I could get the OS and version of TeamCity and version of the webhooks plugin.

**Comment by westshawn** [comment] 2016-08-30 20:19
I'm still trying to reproduce the error. In the mean time, here are my settings.

plugin-settings.xml:
`<?xml version="1.0" encoding="UTF-8"?>
<settings>
  <webhooks enabled="true">
    <webhook url="http://some.web.page:8080/a/folder" enabled="false" format="json" template="none">
      <states>
        <state type="buildSuccessful" enabled="true" />
        <state type="buildBroken" enabled="false" />
        <state type="buildFailed" enabled="true" />
        <state type="buildStarted" enabled="true" />
        <state type="buildFixed" enabled="false" />
        <state type="buildFinished" enabled="true" />
        <state type="responsibilityChanged" enabled="true" />
        <state type="changesLoaded" enabled="true" />
        <state type="buildInterrupted" enabled="true" />
        <state type="beforeBuildFinish" enabled="true" />
      </states>
      <build-types enabled-for-all="true" enabled-for-subprojects="true" />
    </webhook>
  </webhooks>
</settings>`

Server Info:
CentOS Linux release 7.1.1503 
TeamCity 10.0.1 (build 42078)
tcWebHooksPlugin-1.1.109.134

**Comment by westshawn** [comment] 2016-08-30 21:17
So far, I have not been able to reproduce this issue.

I tried removing the plugin and reinstalling. 
The error was initially logged just after server startup after the plugin was installed.

Based on the timing, I'm not sure if it was due to editing webhook settings, or part of server startup.

Though, the error was logged prior to the build running.

**Comment by netwolfuk** [comment] 2016-08-30 21:21
Thanks for the further investigation. I'll update my TC to 10.0.1 (from 10.0.0) and try to reproduce.

**Comment by westshawn** [comment] 2016-08-30 21:22
Got it!
Navigate to build config overview page.
Click on "WebHooks" tab.
In the bottom section under the build config, click on "Add build WebHooks" link.
`WebHooks configured for Build Sandbox > testBuild
There are no WebHooks configured for this specific build.
Add build WebHooks.`

**Comment by netwolfuk** [comment] 2016-08-30 21:26
Ah!  Well done. This is a duplicate of #41 
I had just not taken the time to investigate the associated stack-trace yet. Thanks for the reminder

**Closed** 2016-09-08 10:51 UTC
Labels: bug

**Comment by westshawn** [comment] 2016-09-08 18:13
Verified this is fixed in tcWebHooksPlugin-1.1-alpha7.122.138
* TeamCity 10.0.1 (build 42078)
* CentOS Linux release 7.1.1503 

Thanks for the quick turn-around @netwolfuk !

**Comment by netwolfuk** [comment] 2016-09-08 18:41
Great. Thanks.
