### ISSUE TITLE
webhook does not fire on build change from success to failure, or failure to success

### ISSUE THREAD

**Issue by drewgrubb-runtime** [tcplugins/tcWebHooks#76] opened 2017-11-09 23:12 UTC
I have a webhook configured to post to a slack channel. The message is successfully sent and received on repeated successes and on repeated failures, but the build that transitions from pass to fail or fail to pass is never reported. In the illustration below, the bolded builds will not report, while the rest do. 
P - P - P - P - **F** - F - F - **P** - **F** - **P** - P - P

**Comment by netwolfuk** [comment] 2017-11-10 00:12
Thanks for taking the time to report this issue. I've not seen this before.

To aid in investigating it, is there a chance you could paste the config for this webhook from your `plugin-settings.xml`?  It'd be best to remove your slack API key first.

Also, which versions of teamcity and tcwebhooks are you running? Thanks.

**Comment by netwolfuk** [comment] 2017-11-10 01:09
I just found that one can easily see the content of the plugin-settins.xml file from within the TeamCity UI. 
Go to <your_teamcity>/admin/admin.html?item=diagnostics&tab=dataDir and then drill down to `config/projects/<your_project>/pluginData/plugin-settings.xml`

**Comment by netwolfuk** [comment] 2017-11-28 17:22
Hi @drewgrubb-runtime  Did you get a chance to dig out your plugin settings file?

**Comment by netwolfuk** [comment] 2017-12-06 02:39
I can't reproduce this on 1.1alpha13 (to be released today). I suspect any issue you were seeing may be fixed in alpha12 by better error handling.
Can you upgrade to the latest version and re-test?

**Closed by netwolfuk** 2017-12-06 02:39 UTC
Labels: awaiting feedback
