### ISSUE TITLE
Warnings in teamcity-server.log

### ISSUE THREAD

**Issue by ogerovich** [tcplugins/tcWebHooks#153] opened 2020-03-12 19:43 UTC
## Expected Behavior
No WARN messages from the plugin.

## Current Behavior
```
[2020-03-12 15:39:16,252]   INFO - rver.plugins.PluginsCollection - Load shared classloader for 0 plugins []
[2020-03-12 15:39:16,253]   INFO - rver.plugins.PluginsCollection - Load standalone classloaders for 1 plugins [tcWebHooks]
[2020-03-12 15:39:16,435]   INFO -   jetbrains.buildServer.SERVER - WebHookPayloadManager :: Starting
[2020-03-12 15:39:16,445]   INFO -   jetbrains.buildServer.SERVER - WebHookAuthenticatorProvider :: Starting
[2020-03-12 15:39:16,468]   INFO -   jetbrains.buildServer.SERVER - WebHookTemplateManager :: Starting (webhook.teamcity.payload.WebHookTemplateManager@69715756)
[2020-03-12 15:39:16,502]   INFO -   jetbrains.buildServer.SERVER - WebHookListener ::  :: Starting
[2020-03-12 15:39:16,507]   INFO -   jetbrains.buildServer.SERVER - WebHookListener ::  :: Registering
[2020-03-12 15:39:16,527]   WARN - .InstantiationStrategySelector - Spring selected non-public constructor to create instance: protected webhook.teamcity.extension.WebHookProjectTabExtension(jetbrains.buildServer.web.openapi.PagePlaces,jetbrains.buildServer.serverSide.ProjectManager,jetbrains.buildServer.serverSide.settings.ProjectSettingsManager,jetbrains.buildServer.web.openapi.PluginDescriptor,webhook.teamcity.history.WebHookHistoryRepository,webhook.teamcity.history.WebAddressTransformer)
[2020-03-12 15:39:16,534]   WARN - .InstantiationStrategySelector - Spring selected non-public constructor to create instance: protected webhook.teamcity.extension.WebHookBuildTypeTabExtension(jetbrains.buildServer.serverSide.ProjectManager,jetbrains.buildServer.serverSide.settings.ProjectSettingsManager,jetbrains.buildServer.web.openapi.WebControllerManager,jetbrains.buildServer.web.openapi.PluginDescriptor,webhook.teamcity.history.WebHookHistoryRepository,webhook.teamcity.history.WebAddressTransformer)
[2020-03-12 15:39:16,571]   INFO -   jetbrains.buildServer.SERVER - EndPointController:: Registering
[2020-03-12 15:39:16,577]   INFO -   jetbrains.buildServer.SERVER - EndPointController:: Registering
```

## Steps to Reproduce (for bugs)
1. Upload the plugin to the server that never had it and enable it or restart a server that had it
2. Check teamcity-server.log.

## Your Environment

* tcWebHooks Version: 1.1.355.396
* TeamCity Version: 2019.2.2
* TeamCity server Operating System: Windows 10
* Are you using a WebHook Template?: No

**Comment by netwolfuk** [comment] 2020-03-12 22:28
Hi @ogerovich. Thanks taking the time to report this.
Last time I saw this I thought that the problem is because I'm extending the TeamCity provided classes for this stuff, but I'll take another look.

Do you work with jetbrains? Is this a solvable problem, and I'm doing something wrong?

**Comment by netwolfuk** [comment] 2020-03-12 22:35
Oh. Looking at the code this should have a public constructor. I'll try to fix over the weekend.

**Comment by ogerovich** [comment] 2020-03-13 13:06
Hi @netwolfuk.
I'm a JetBrains customer and use TeamCity along with your plugin. Unfortunately, I'm not very familiar with plugins to recommend anything. I just noticed these warnings and wanted to let you know.

**Comment by netwolfuk** [comment] 2020-03-13 18:19
Thanks. That's cool. 

I've fixed the issue, I just want to do some more testing and will do a release this weekend.

**Comment by netwolfuk** [comment] 2020-03-16 10:12
Release. Closing ticket.

**Closed by netwolfuk** 2020-03-16 10:12 UTC

**Comment by ogerovich** [comment] 2020-03-16 13:57
Thank you. I deployed the plugin. No more warnings.

**Comment by netwolfuk** [comment] 2020-03-16 17:54
Great. Thanks for the feedback
